language: go
os:
  - linux
  - osx
go:
  - stable
  - "1.13"
  - "1.12"
  - "1.11"
  matrix:
    include:
    - os: osx
      osx_image: xcode10.1
    fast_finish: true
install:
  - go get -t ./...
  - go get github.com/mattn/goveralls
script:
  - goveralls -v -service=travis-ci
